### ISSUE TITLE
El texto "Abrir contenido" no deja margen a la derecha

### ISSUE THREAD

**Issue by drnachio** [BinPar/eBooks#10]
Debería ser el mismo que hay a la izquierda de la flecha de anterior:

<img width="723" alt="captura de pantalla 2016-10-04 a las 9 32 30" src="https://cloud.githubusercontent.com/assets/5763165/19065756/9f0aa4e8-8a15-11e6-9366-509c54e606a4.png">

**Comment by nazaBinpar** [comment]
Hecho http://www.medicapanamericana.com/digital/ebooks/buscador#
