### ISSUE TITLE
El valor no puede ser nulo en EbooksController.cs:línea 159

### ISSUE THREAD

**Issue by drnachio** [BinPar/eBooks#12]
Event code: 3005 
Event message: Excepción no controlada. 
Event time: 04/10/2016 6:17:51 
Event time (UTC): 04/10/2016 4:17:51 
Event ID: 33fc573d67c04b97929e5d6aaf082e67 
Event sequence: 3693 
Event occurrence: 27 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/drm-1-131199840017309669 
    Trust level: Full 
    Application Virtual Path: /drm 
    Application Path: C:\webs\drm\ 
    Machine name: NS3024562 
 
Process information: 
    Process ID: 9148 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\DRM 
 
Exception information: 
    Exception type: ArgumentNullException 
    Exception message: El valor no puede ser nulo.
Nombre del parámetro: contents
   en System.IO.File.AppendAllLines(String path, IEnumerable`1 contents)
   en DRM.MVC.Controllers.EbooksController.CanAccess(String[] ips, String referrer, String netSessionId, String isbn, Nullable`1 userID, Guid sessionId, String browser, String device) en C:\Proyectos Compartidos\PanamericanaCounter\DRM.MVC\Controllers\EbooksController.cs:línea 159
   en lambda_method(Closure , ControllerBase , Object[] )
   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   en System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   en System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: http://www.medicapanamericana.com/drm/ebooks/canaccess 
    Request path: /drm/ebooks/canaccess 
    User host address: 127.0.0.1 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\DRM 
 
Thread information: 
    Thread ID: 48 
    Thread account name: IIS APPPOOL\DRM 
    Is impersonating: False 
    Stack trace:    en System.IO.File.AppendAllLines(String path, IEnumerable`1 contents)
   en DRM.MVC.Controllers.EbooksController.CanAccess(String[] ips, String referrer, String netSessionId, String isbn, Nullable`1 userID, Guid sessionId, String browser, String device) en C:\Proyectos Compartidos\PanamericanaCounter\DRM.MVC\Controllers\EbooksController.cs:línea 159
   en lambda_method(Closure , ControllerBase , Object[] )
   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   en System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   en System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by FaustoBinpar** [comment]
He controlado si el valor es nulo no lance la excepción.
