### ISSUE TITLE
1092016 Acceso token Casa Tierra de Fuego - Argentina

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#14]
En esta institución ahora mismo están accediendo mediante URL referida a Eureka. Los reponsables de la institución nos preguntan: con un acceso token, qué tendrían que hacer para que los usuarios sean reconocidos por EMP y no deban registrarse de nuevo en la web de EMP para poder subrayar y marcar los títulos en el visor.
Esto sería posible?
Gracias

**Comment by CristianBinpar** [comment]
Necesitaríamos hacer un **desarrollo específico** donde por **parámetro** nos indicasen el id de matricula o el id de usuario para poder generar un usuario al vuelo. También exige un cambio en su código fuente para generar estas URLs.

Además, hay que tener en cuenta las partes negativas de hacer esta implementación. Por ejemplo, si acceden por token y se crean un usuario y en el futuro compran la obra y no pertenecen a la institución conservarían todo su trabajo previo.

Teniendo en cuenta que existe el registro ligero parece recomendable que se diesen de alta.

**Comment by ajarillo** [comment]
OK, he informado a Diego Moreno en Argentina. Dejo abierto el tema, de momento por si necesitan más información al respecto.
Gracias
