### ISSUE TITLE
1102016 Título: Vacunación en adultos y mayores no aparece en DRM

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#19]
El título: Vacunación en adultos y mayores (http://www.medicapanamericana.com/Libros/Libro/5610/eBook-Vacunacion-en-Adultos-y-Mayores.html) no aparece en DRM.

**Comment by ajarillo** [comment]
Hola, necesito habilitar este título para La Universidad Francisco de vitoria y sigo sin poder hacerlo, sabéis qué ocurre? No aparece en el listado del DRM.
Gracias

**Comment by CristianBinpar** [comment]
@ajarillo 

sí aparece, el eBook es el siguiente:
http://gestor.medicapanamericana.com/tables/ebook.aspx?id=58263

podría estar mal catalogado por nombre.

**Comment by ajarillo** [comment]
Están cruzados título y subtítulo, se puede modificar?
Es que sino, la próxima vez me ocurrirá lo mismo o a México o el resto de filiales que comiencen a utilizar DRM.
Gracias

**Comment by CristianBinpar** [comment]
Creo que no debería haber problema
