### ISSUE TITLE
1002016 16-09-23 Reporte Escuela Médico Militar de Odontología

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#2]
Institución: Escuela Médico Militar de Odontología
http://gestor.medicapanamericana.com/tables/institution.aspx?id=353
Estantería
Acceso a su plataforma: URL: https://educacionvirtual.sedena.gob.mx/course/view.php?id=476 
USUARIO: medicapanamericana
CONTRASEÑA: PANA#mericana.2016
Descripción: Al ingresar a un eBook, solo se muestra su información por unos segundos, posteriormente se le solicita al usuario que se registre para acceder al título. Adjuntamos captura de pantalla.
Navegador y dispositivos utilizados: Google Chrome e Internet Explorer - PC
[1002016 16-09-23 Reporte Escuela Médico Militar de Odontología.xlsx](https://github.com/BinPar/eBooks/files/500074/1002016.16-09-23.Reporte.Escuela.Medico.Militar.de.Odontologia.xlsx)
[1002016 16-09-23 Screenshot Reporte Escuela Médico Militar de Odontología.docx](https://github.com/BinPar/eBooks/files/500075/1002016.16-09-23.Screenshot.Reporte.Escuela.Medico.Militar.de.Odontologia.docx)

**Comment by CristianBinpar** [comment]
A expensas de verificación por la institución.

Con la última subida de versión debería estar solucionado.

**Comment by ajarillo** [comment]
Acabo de comprobarlo con las credenciales que nos dieron desde la institución y todo correcto. Avisados compañeros de México.

**Comment by ajarillo** [comment]
Nos escribe Silvia de México. El acceso a cada título, les deja visualizar el mismo por unos segundos pero después les lleva a una página para

 que se registren. Adjunto pantallazos con IP utilizada que envía Silvia. Podeis verlos aquí: https://drive.google.com/file/d/0B-MQEOwVhqd0cnprOFZTWDAyTFU/view?usp=sharing

**Comment by ajarillo** [comment]
México nos informa que están perdiendo ventas por estar sin acceso en las instituciones que tienen incidencias abiertas. Aquí tenéis su texto y el archivo que nos adjunta:

_Hola Alicia, 

Buen día, ¿habrá noticias sobre este tema? Disculpa que te insista, créeme que entendemos la necesidad de que Binpar se concentre en arreglar las fallas generales de la plataforma y los eBooks, pero la institución lleva 3 semanas sin acceso, sus estudiantes están en exámenes y no pueden revisar el material, teníamos la posibilidad de una compra adicional que difícilmente lograremos rescatar considerando que al día de hoy no hemos podido darle solución al problema. 

Te adjunto la pantalla de la prueba que he realizado hoy y en la que podrás ver que el problema persiste. 

Estamos al pendiente. 

Saludos 
Silvia Ernestina Pérez Cordero
[16-10-13 Escuela Médico Militar de Odontología.docx](https://github.com/BinPar/eBooks/files/527829/16-10-13.Escuela.Medico.Militar.de.Odontologia.docx)
_

**Comment by ajarillo** [comment]
Acabo de comprobar de nuevo el acceso y efectivamente, tras mostrar un segundo el contenido del título, muestra la página que veis en los pantallazos del registro ligero con la portada de uno de los títulos.
Por favor, decidnos algo al respecto.
Gracias

**Comment by CristianBinpar** [comment]
Detectado el problema.

Tiene que ver con que nos llaman al DRM a partir de HTTPS. Lo solucionamos y subimos versión para que sea robusta a esta llamada en todos los casos futuros.

**Comment by ajarillo** [comment]
Gracias. Esperamos vuestra señal para volver a probar y avisar a México.

**Comment by FaustoBinpar** [comment]
Buenas, esta arreglado, podéis hacer pruebas

**Comment by ajarillo** [comment]
Gracias, qué buena noticia!! 
Acabo de probar y parece que todo está ok. Ya he escrito a México para que avisen a la institución.
Gracias
