### ISSUE TITLE
1122016 Identificación para descarga de imágenes

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#21]
Prueba con IP 79.145.162.239 fecha 2016-10-05 15:45 h
PC Chrome
Institución del DRM Departamento de Productos Digitales
En la previsualización hago clic sobre una imagen y se amplía en el centro, clic sobre flecha blanca sobre verde y salta el mensaje de Iniciar sesión. Cambia la pantalla de la izquierda (no desaparece la imagen ampliada en el centro de la pantalla) y pide usuario y contraseña. En ningún momento da la opción de registro ligero. Cómo pueden descargarse las imágenes entonces?
![registro de descarga de imagenes](https://cloud.githubusercontent.com/assets/22492646/19115819/9e507d94-8b13-11e6-81e0-3c0e6a138654.png)

**Comment by CristianBinpar** [comment]
Publicamos versión con la solución

**Comment by ajarillo** [comment]
Si nos situamos sobre el botón de registro no aparece el cursor con forma de mano. El texto de Registro está muy cerca del de Acceder. Lo podéis modificar?
Gracias

**Comment by CristianBinpar** [comment]
Si sí,

vamos a mejorar estilos en el día de hoy.
