### ISSUE TITLE
1142016 Descarga de imágenes desde Firefox

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#23]
- Por Eureka mediante IP desde Firefox si hago clic sobre la flecha de descarga de una imagen en la previsualización e introduzco mi usuario de EMP ajarillo@medicapanamericana.es me dice que el usuario no tiene permisos (creo que se cree que quiero acceder a la zona de las estadísticas y como no tengo permisos en el gestor para esa institución igual no me deja).
- Si intento la descarga desde Firefox, a través Mis ebooks (usuario: ajarillo@medicapanamericana.es) de la web, desde el visor, al hacer clic sobre la flecha de descarga, no pasa nada. Adjunto imagen.
  ![descarga imagenes desde firefox](https://cloud.githubusercontent.com/assets/22492646/19146206/d6de8bd4-8bb2-11e6-8937-d89003b503c9.png)

**Comment by ajarillo** [comment]
La universidad de Sevilla acaba de suscribir Eureka, y están pendientes de este punto.

**Comment by CristianBinpar** [comment]
Publicamos versión

**Comment by ajarillo** [comment]
Gracias. Informada la institución y solicitada confirmación por su parte.

**Comment by ajarillo** [comment]
Hola,
La descarga de imágenes está disponible desde el visor, pero desde Eureka sigue sin funcionar.
Por ejemplo en el título Neuropsicología de la adicción:
![www medicapanamericana com_2016-10-24_11-21-52](https://cloud.githubusercontent.com/assets/22492646/19640921/32c59674-99df-11e6-88b8-9e46837201c0.png)
![www medicapanamericana com_2016-10-24_11-22-03](https://cloud.githubusercontent.com/assets/22492646/19640923/376c42a4-99df-11e6-8b2a-0cb63e0dbf33.png)
Como podéis ver no está la flecha verde y por tanto no hay opción a registro.
Decidnos cuando podría estar solucionado, por favor.
Gracias

**Comment by CristianBinpar** [comment]
@ajarillo 

a mi me funciona bien, te adjunto pantalla:

![image](https://cloud.githubusercontent.com/assets/17255550/20066943/a6f3e192-a513-11e6-899b-a0a7455b5b38.png)

¿Podrías enviar más información?

**Comment by CristianBinpar** [comment]
@FaustoBinpar  Hay que revisar la descarga en Firefox, es cierto que no se produce.
