### ISSUE TITLE
Incidencia Panamericana - Colegio fisioterapeutas de Madrid y de Barcelona

### ISSUE THREAD

**Issue by Julbesito** [BinPar/eBooks#24]
Os paso el error que les sucede a menudo al Colegio de Fisioterapeutas de Madrid y también les pasa al colegio de Barcelona. 
Cuando tratan de consultar alguno de los libros de Panamericana les aparece una pantalla como la que ves más abajo. Parece ser que se soluciona borrando la caché del navegador, pero no debería pasar este problema.

![20161007 colegio de fisioterapeutas](https://cloud.githubusercontent.com/assets/22503990/19180790/e2abc90c-8c68-11e6-8a6c-6e493e9500bc.png)

**Comment by CristianBinpar** [comment]
Podría estar solucionada con el cambio de código

**Comment by ajarillo** [comment]
El cliente aún no ha confirmado, pero como consideramos que ya ha pasado suficiente tiempo y aún no tenemos feedback damos tema por cerrado.
