### ISSUE TITLE
1152016 Universidad de Sevilla sin Eureka ni visor

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#26]
La Universidad de Sevilla nos dice que no puede acceder al visor ni a Eureka.
Acaban de suscribir Eureka.
Adjunto imágenes.

![use_01](https://cloud.githubusercontent.com/assets/22492646/19268656/e953796c-8fb5-11e6-84c6-088778d5df79.png)
![use](https://cloud.githubusercontent.com/assets/22492646/19268657/e9558f90-8fb5-11e6-9092-6eb36035a2ef.png)

**Comment by ajarillo** [comment]
IP prueba 79.145.162.239
Acabo de eliminar las dos licencias de ebooks que tenía esta universidad y el error de la segunda imagen seguía siendo el mismo. He dejado dos licencias para Eureka, una de junio a diciembre 2016 con  x+1 títulos y otra de enero-diciembre 2017 con x títulos. Mismo error.
Después he ampliado la licencia junio a diciembre 2016 a diciembre 2017 y el mensaje de error de la segunda imagen cambiaba a "activa a partir del 1 de enero de 2017".
El último paso que he dado ha sido eliminar la licencia enero-diciembre 2017 y dejar sólo una de junio 2016 a diciembre 2017. Con esto se ha solucionado el problema de acceso que tenía la universidad, ero genera nuevas dudas. No podemos tener más de una licencia de Eureka en una institución? Una estaba activa y la otra aún no había comenzado. Cambio de crítico a medio.

**Comment by CristianBinpar** [comment]
Estamos comentando con Manuel, que las licencias de Eureka sin necesidad de licencias eBooks no tienen caracter retroactivo.

En principio, tratar de emplear una única licencia Eureka.
