### ISSUE TITLE
1162016 DTM Universidad de Navarra

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#27]
Institución: Universidad de Navarra
Gestor DRM: http://gestor.medicapanamericana.com/tables/institution.aspx?id=226
Una vez cada dos meses aproximadamente les ocurre que les llega el mensaje del DTM de los accesos concurrentes superados y no pueden acceder hasta que no se los reiniciais. Normalmente lo reiniciais y ya está, pero podemos hacer algo más para que no les llegue este email y no vuelvan a quedarse sin acceso?
Compraron el DTM en permanente. Cuántos usuarios simultáneos tienen?
Ahora mismo están sin acceso. Ya nos contáis.

**Comment by CristianBinpar** [comment]
Necesitaría un desarrollo importante.

Aumentar accesos en DRM como solución consensuada con Manuel.

**Comment by ajarillo** [comment]
Me dice Manuel sobre esta incidencia que debemos ampliar nosotros los accesos desde el DRM. Esto nunca se ha hecho así, estáis seguros? Siempre para los temas de DTM los hacéis vosotros directamente.
Habéis reiniciado de todas formas el acceso para que la universidad pueda entrar de nuevo en el DTM?

**Comment by CristianBinpar** [comment]
Aumentaremos a 100 accesos

**Comment by FaustoBinpar** [comment]
Buenas
En la siguente Institución: Universidad de Navarra
Gestor DRM: http://gestor.medicapanamericana.com/tables/institution.aspx?id=226

No veo que tenga licencias de DTM

Es correcto el enlace al gestor?

**Comment by ajarillo** [comment]
Hola,
Si, es correcto. 
Por favor actívales una licencia de DTM con 100 accesos.
Gracias

**Comment by ajarillo** [comment]
Hola, finalmente esto se hizo hoy?
Si no lo podréis hacer mañana?
Gracias
Alicia

**Comment by ajarillo** [comment]
Hola, llevan sin acceso ya varios días.
Por favor, darle prioridad.
Gracias

**Comment by miguelBinpar** [comment]
Buenas tardes,

Estoy revisando este tema. Vamos por partes:

No es necesario crear ninguna licencia, ya existe un acceso para esta universidad. Eso sí, es realmente viejo. Si no me equivoco hablamos del primer acceso por IP que se generó para el DTM, antes de que existiera el DRM, incluso antes del sistema previo de acceso por IP. Esto significa que en lugar de un usuario "ficticio", que es lo que utilizamos actualmente para relacionar a cada institución con su acceso, en este caso se utilizó un usuario normal.

Dicho usuario tiene el email jfvilla@unav.es. Su ID en base de datos es 7197 (http://gestor.medicapanamericana.com/tables/user.aspx?id=7197).

Una vez llegado al usuario, podemos ver sus suscripciones:
http://gestor.medicapanamericana.com/tables/additionaSubscription.aspx?id=3873
http://gestor.medicapanamericana.com/tables/additionaSubscription.aspx?id=1327

Una caducó hace años y la otra es permanente.

Si os fijáis en la permanente, veréis que el día 24 se establecieron manualmente los warnings a 6 (podéis comprobar el historial de cambios), bloqueando el acceso mediante dicho cambio.

Con el cambio a -500 (para evitar que salten los warnings continuamente, como ya hicimos con alguna otra universidad) debería pasar cierto tiempo hasta volver a encontrarnos con el problema. Aún así, la diferencia entre el DTM y el DRM a la hora de controlar los accesos es algo que se debería tratar en algún momento.

Un saludo.
