### ISSUE TITLE
1012016 16-09-26 Reporte Escuela Médico Militar de Odontología

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#3]
Institución: SDN Escuela Médico Militar
http://gestor.medicapanamericana.com/tables/institution.aspx?id=391
Estantería
Acceso para prueba: https://educacionvirtual.sedena.gob.mx/course/view.php?id=453
USUARIO: editorialmedicapanamericana
CONTRASEÑA: SEM_bibliotemm_337

1. Si intentamos acceder a la plataforma desde Internet Explorer, nos envía a la sección de Instituciones de nuestra Web. Incluimos captura.
¿Cómo puede ser que si accedo desde Chrome no tenga ningún problema?
2. Estando dentro del eBook no se realizan búsquedas en el diccionario, solo las hace sobre el texto de la obra que se está consultando. Esta prueba la realicé con Google Chrome desde mi PC, en el eBook de Neurología de MICHELI | FERNÁNDEZ PARDAL con EAN 9789500604819, la búsqueda la hice con la palabra Neurología y como podréis observar en el documento adjunto al final de todos los resultados no aparece la definición del DTM. A MAnuel le ha pasado a la largo de esta semana en varias demostraciones de Eureka también.
[1012016 16-09-26 Reporte Escuela Médico Militar de Odontología.xlsx](https://github.com/BinPar/eBooks/files/500085/1012016.16-09-26.Reporte.Escuela.Medico.Militar.de.Odontologia.xlsx)
[1012016 16-09-26 Screenshot Escuela Médico Militar de Odontología.docx](https://github.com/BinPar/eBooks/files/500086/1012016.16-09-26.Screenshot.Escuela.Medico.Militar.de.Odontologia.docx)
[1012016 16-09-26 Reporte Escuela Médico Militar de Odontología.xlsx](https://github.com/BinPar/eBooks/files/500097/1012016.16-09-26.Reporte.Escuela.Medico.Militar.de.Odontologia.xlsx)
[1012016 16-09-26 Screenshot Escuela Médico Militar de Odontología.docx](https://github.com/BinPar/eBooks/files/500098/1012016.16-09-26.Screenshot.Escuela.Medico.Militar.de.Odontologia.docx)

Navegador y dispositivo utilizados: Google Chrome e Internet Explorer - PC
[1012016 16-09-26 Reporte Escuela Médico Militar de Odontología.xlsx](https://github.com/BinPar/eBooks/files/500133/1012016.16-09-26.Reporte.Escuela.Medico.Militar.de.Odontologia.xlsx)
[1012016 16-09-26 Screenshot Escuela Médico Militar de Odontología.docx](https://github.com/BinPar/eBooks/files/500134/1012016.16-09-26.Screenshot.Escuela.Medico.Militar.de.Odontologia.docx)

**Comment by CristianBinpar** [comment]
A expensas de verificación por la institución.

Con la última subida de versión debería estar solucionado.

**Comment by ajarillo** [comment]
IP: 79.145.162.239
Hora: 15:41
Realizo prueba con los datos de acceso que nos facilitan en esta incidencia. Eureka abre y busca, pero en la previsualización de la derecha no aparece nada, todo el timepo la e de Eureka con fondo gris cargando. Si pincho en abrir contenido directamente desde la izquierda abre el visor sin problema.
La previsualización en ocasiones ocurre lo que adjunto en el pantallazo, que se ve en la izquierda en vez de en la derecha. Título: Inmunología. Autor: Rojas
![previsualizacion de eureka - izquierda](https://cloud.githubusercontent.com/assets/22492646/19272582/62fc5b2c-8fc9-11e6-9229-b9d889002e72.png)

**Comment by ajarillo** [comment]
Acabo de probar y todo sigue igual que la última actualización, por favor, Decidnos algo sobre esto.
Como ya os he comentado esta mañana, aunque tenéis todo lo que necesitáis para realizar las pruebas; IPs de pruebas, navegadores utilizados, fechas y horas, pantallazo, calves para probarlo vosotros mismos, ...
Quedamos a la espera.
Gracias

**Comment by CristianBinpar** [comment]
Alicia,

os pasamos el log de peticiones de esta institución para cada navegador, donde se ve que por alguna razón **no nos envían la URL referida** desde Explorer:

Intenet Explorer
### 17/10/2016 9:47:10
- NetSessionId: nj1bpxtrgn5jhwstlozov2pk
- Server Request Session Id h5xn5b3ybcni0rgfpdpfhtyb
- IP's: 80.28.219.213, 
- UserID: Sin usuario logueado
- Referrer: 
- SESSION ID: 00000000-0000-0000-0000-000000000000
- PrevReferrer: 
- LicenseID: Sin licencia
- AccessType: None
- AccessMode: None
- RejectedReason: NoUserNoLicense



Mozilla
### 17/10/2016 9:47:50
- NetSessionId: 1fgbt3cmi1nt0rg2w3fjiec4
- Server Request Session Id a5fp5zgg5f4xff2wfo3xd2k1
- IP's: 80.28.219.213, 
- UserID: Sin usuario logueado
- Referrer: https://educacionvirtual.sedena.gob.mx/course/view.php?id=453
- SESSION ID: 5155dc9e-5aa4-497b-970b-ed4865e63dff
- PrevReferrer: 
- LicenseID: 900
- AccessType: ByLicense
- AccessMode: ByUrlRefered
- SessionID: 5155dc9e-5aa4-497b-970b-ed4865e63dff
- Master UserID: 778963
- User Email: sdnescuelamedicomilitar@drm.medicapanamericana.com
- User Password: 15f383e6-c013-4e01-bfe2-9e0e74acdb91


Chrome
### 17/10/2016 9:45:23
- NetSessionId: pqrd54l5kljlwz102n4ib55p
- Server Request Session Id uhyg4ra22a1smpgeyf4s0maf
- IP's: 80.28.219.213, 
- UserID: Sin usuario logueado
- Referrer: https://educacionvirtual.sedena.gob.mx/course/view.php?id=453
- SESSION ID: 00000000-0000-0000-0000-000000000000
- PrevReferrer: 
- LicenseID: 900
- AccessType: ByLicense
- AccessMode: ByUrlRefered
- SessionID: 38a2d800-546c-4288-a0c6-7ff0d15294e7
- Master UserID: 778963
- User Email: sdnescuelamedicomilitar@drm.medicapanamericana.com
- User Password: 15f383e6-c013-4e01-bfe2-9e0e74acdb91

Edge
### 17/10/2016 9:42:12
- NetSessionId: rw2qiizyosbhcfebj43lnb34
- Server Request Session Id xkn0meeh5g0tgdb1d0waw0la
- IP's: 80.28.219.213, 
- UserID: Sin usuario logueado
- Referrer: https://educacionvirtual.sedena.gob.mx/course/view.php?id=453
- SESSION ID: 00000000-0000-0000-0000-000000000000
- PrevReferrer: 
- LicenseID: 900
- AccessType: ByLicense
- AccessMode: ByUrlRefered
- SessionID: 85fead8f-162d-4509-9458-d380e8197556
- Master UserID: 778963
- User Email: sdnescuelamedicomilitar@drm.medicapanamericana.com
- User Password: 15f383e6-c013-4e01-bfe2-9e0e74acdb91

¿podrían revisar el proceso?

**Comment by ajarillo** [comment]
Gracias. Entonces se supone que con todos los navegadores, menos con IE ya debería funcionar? Es que yo las pruebas las hice con GChrome y la previsualización no funciona, puedes ver la captura y los detalles de la prueba en la actualización que hice esta incidencia el viernes.
No obstante acabo de enviar la información sobre los logs a México para que se lo pregunten a la institución. 
Mientras tanto, cuando podáis revisar el tema de la previsualización.
El DTM ya funciona correctamente.

**Comment by CristianBinpar** [comment]
Detectado el problema. Subiremos el cambio en breves

**Comment by CristianBinpar** [comment]
Águeda modificará los script de los eBooks que tuviesen este problema.

**Comment by ajarillo** [comment]
Hola,
Silvia nos escribe esto:
_Te comento que la incidencia que habíamos reportado de la SDN Escuela Médico Militar ya ha sido solucionada, imagino que estaba relacionada con el problema de la ULA y que el lunes que arreglaron ese detalle, automáticamente afectó también el acceso de esta escuela, quedando todo arreglado._

**Comment by CristianBinpar** [comment]
Si, ya estaba solucionada Alicia,

gracias por el aviso.
