### ISSUE TITLE
1202016 Revisión compatibilidad Vademécum Internacional

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#31]
Nos vuelven a enviar los datos del libro Vademécum internacional, parece que ahora dicen que sí seremos compatibles. Hace poco creo que lo revisó Águeda, cuando pueda que le eche un vistazo y nos cuente, por favor.
Podéis encontrar la información: 
https://www.dropbox.com/sh/4co1snw6eq6agaf/AADaaFfKW1qxSoupo5JnDcMoa?dl=0
Gracias

**Comment by AguedaBinpar** [comment]
Confirmo que el problema de superposición de páginas que tenían los epubs y que aparecáin en los pdfs resusltantes ya no se dan... paso a testear los pdfs

**Comment by AguedaBinpar** [comment]
Prueba de conversión de uno de los pdfs (ESP) en el test del CRM es buena

necesito un isbns y que se den de alta para probar a convertir en el visor

Aunque puedo hacer una primera prueba en mi isbn con uno de ellos

**Comment by AguedaBinpar** [comment]
Alicia

aquí lo tienes el trocito que he convertido de prueba

http://www.medicapanamericana.com/VisorEbookV2/Ebook/0000000000002#{"Pagina":"1","Vista":"Miniaturas","Busqueda":""}
