### ISSUE TITLE
1212016 Renovación DTM Universidad Pablo de Olavide

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#32]
Institución: http://gestor.medicapanamericana.com/tables/institution.aspx?id=280
Necesitamos renovar hasta el 31 de diciembre de 2017 el DTM por IP para esta institución. Les ocurre igual que a la universidad de Navarra, que e vez en cuando se les bloquea y les llega el mail de que les han pirateado la cuenta. Por favor, a parte de ampliar la fecha ampliar el numero de accesos tanto como sea necesario para que nos les vuelva a llegar ese mensaje.

**Comment by CristianBinpar** [comment]
Vamos a cambiar a 100

**Comment by FaustoBinpar** [comment]
Cambio realizado

**Comment by ajarillo** [comment]
Gracias Fausto.
Buen día.
