### ISSUE TITLE
1232016 9788498359015 Cuidados Paliativos

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#34]
En la previsualización no se abren las pantallas emergentes con las imágenes (Gonzalez Cuidados Paliativos, P. 205 llamado Fig. 13-1, P. 204 llamado a Tabla 13-2) ni en Eureka ni en el visor, comprobado con navegadores GChrome y Firefox

**Comment by CristianBinpar** [comment]
Es un libro realizado en EMP.

Está hipervinculado, pero falta la carpeta de imágenes. 

Parece que se olvidaron de subir la carpeta.
