### ISSUE TITLE
URGENTE 1242016 Universidad Latinoamericana desde qué URL nos llega la petición

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#35]
IP: 204.17.19.20
Dispositivo: PC
Navegador: Google Chrome
Fecha y Hora: 12 de octubre de 2016 a las 05:01 p.m. (Ciudad de México)
Modalidad: Acceso por URL Referida a Eureka
Título al que se accedió: Buscador Eureka

En DRM tenemos una URL referida que nos dieron pero parece ser que no es la adecuada porque no pueden entrar en eEureka, encontes han realizado una prueba desde la IP que veis arriba y necesitan saber qué URL es la que nos aparece que ha realizado la petición. Si podemos sacarla para mañana bien, sino, nos piden TLC. Cuando la solicitaros Cristian me comentó que tendría que ser a partir del lunes 17. Si consideráis
[16-10-13 Universidad Latinoamericana.docx](https://github.com/BinPar/eBooks/files/527895/16-10-13.Universidad.Latinoamericana.docx)
 que esto no estará resuelto para mañana, por favor, darnos fecha y hora para la TLC.
Gracias

**Comment by ajarillo** [comment]
Hola, desde México nos piden fecha para una TLC con esta universidad.
Cuándo creéis que podéis hacerla? Necesitan que sea esta semana.
Gracias

**Comment by FaustoBinpar** [comment]
He revisado todos los logs y no he encontrado ningún acceso con la siguiente IP : 204.17.19.20, también he revisado los acceso de la Universidad Latinoamericana a la hora indicada y tampoco veo peticiones de acceso.

**Comment by CristianBinpar** [comment]
Esta semana podría ser el jueves, coméntanos horas posibles.

gracias.

**Comment by ajarillo** [comment]
Gracias. Acabo de preguntar a México. os cuento cuando me digan algo.

**Comment by CristianBinpar** [comment]
Fijada jueves 15.30

**Comment by ajarillo** [comment]
Perfecto, gracias. Silvia de México organizará el GotoMeeting.

**Comment by ajarillo** [comment]
Hola, tal y como habéis visto el la TLC de hoy una vez que entran a Eureka se quedan sin acceso.
Silvia me ha contado que es el mayor cliente de Eureka en México por lo que el que estén sin acceso puede hacernos mucho daño. Aquí tenéis el mensaje que nos ha enviado. Tenéis las claves y url para realizar las pruebas
![ula](https://cloud.githubusercontent.com/assets/22492646/19571029/bc29e70c-96fc-11e6-8470-260bdbe65858.png)
 más abajo.

Hola Silvia y Alicia, buena tarde

      Hemos detectado que hay un error en la plataforma EUREKA que nos está impactando en nuestra Biblioteca Virtual actual, es decir, al entrar no vemos todas las clasificaciones de temas, ni tampoco nos permite acceder a un título ( imágenes más abajo)

Omar en esto caso nos sugiere que una vez se arregle este problema, probablemente ya funcione el acceso para el nuevo proyecto motivo de la llamada que tuvimos en la mañana; debido a que el comportamiento es el mismo, es decir, tanto en la biblioteca virtual actual como en el sitio de prueba del nuevo proyecto.

Reitero es urgente se solucione el problema ya que nuestros estudiantes no pueden acceder.

Te enviamos unas claves de usuarios para que hagan las pruebas pertinentes y quedamos atentos a su retroalimentación, 


USUARIO: BVCL1
PASS: Welcome1
bibliotecavirtual.ula.edu.mx

**Comment by ajarillo** [comment]
Hola, 
el sábado 21 de octubre Belem de México escribió esto:
Estimados revise la plataforma de la ULA en los tres exploradores y este es el resultado en teoría todo está funcionando, usando la última clave de acceso que os compartieron.
![3](https://cloud.githubusercontent.com/assets/22492646/19637605/3c4f149a-99d0-11e6-8acc-7ed46d99aefd.jpg)
![2](https://cloud.githubusercontent.com/assets/22492646/19637604/3c4cee86-99d0-11e6-9eba-b53e5786f541.jpg)
![1](https://cloud.githubusercontent.com/assets/22492646/19637610/403bc314-99d0-11e6-8a5d-55833efca073.jpg)


Habéis realizado algún cambio durante el fin de semana? ¿Cómo es que ya funciona? Gracias

**Comment by CristianBinpar** [comment]
@ajarillo este ya estaba solucionado.
