### ISSUE TITLE
Colombia Caida de ebooks en clientes

### ISSUE THREAD

**Issue by Julbesito** [BinPar/eBooks#36]
Hola Ronald nos manda mail para informarnos de caida general del sistema en Colombia.
El sistema no es estable, eso parece. Le hemos pedido pantallazo. La informaqcion que nos dicen es que les lleva a acceso a bibliotecas.

De: Ronald Oswaldo Rodríguez Otálora [mailto:rrodriguez@medicapanamericana.com.co] 
Enviado el: jueves, 13 de octubre de 2016 21:17
Para: 'Alicia Jarillo' <ajarillo@medicapanamericana.es>; 'Manuel Júlbez Campos' <mjulbez@medicapanamericana.es>
CC: Fanny J. Cuervo C. <fcuervo@medicapanamericana.com.co>; E.M.I. PROMOCION 1 Luis Alberto <promocionmp1@medicapanamericana.com.co>
Asunto: Error acceso Ebooks

Hola Alicia,

Otra vez fallando el acceso a los Ebooks y direcciona a Acceso para Bibliotecas.

**Comment by ajarillo** [comment]
Me dijo que no puede enviarnos pantallazos porque después ya funcionaba. Le pedí que la próxima vez hiciera captura, fecha, hora y pantallazo de IP.
Dejo abierta para que Binpar sea consciente y la cierre cuando crea conveniente, pues ya les funciona bien. Al menos de momento.

**Comment by CristianBinpar** [comment]
Anotada la incidencia con las relativas a este tipo de problemas.

gracias
