### ISSUE TITLE
1262016 Compatibilidad de Eureka con Athens, Shibboleth? Linux?

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#38]
Somos compatibles con Athens o Shibboleth? y con Linux? Nos lo ha preguntado UDIMA

**Comment by CristianBinpar** [comment]
@ajarillo 

Con Linux hemos confirmado que sí.

Habría que saber más sobre Athens o Shibboleth, no tenemos información.

**Comment by ajarillo** [comment]
Gracias.
Athens http://www.openathens.org/for-publishers/
Shibboleth https://shibboleth.net/
Diferencias entre ambos: http://www.openathens.org/informationmanager-faqs/difference-shibboleth-openathens/

**Comment by CristianBinpar** [comment]
@ajarillo  creo que tendríais que contactar con ellos para ver lo que debemos hacer para participar.

Casi con seguridad exige un desarrollo, que habría que valorar.
