### ISSUE TITLE
1272016 Caídas puntuales de acceso a Eureka y visor (particulares e instituciones)

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#39]
Según TLC mantenida hoy parece que el servidor se satura y ha habido un aumento de peticiones de acceso. Binpar lo estudiará y propondrá la mejor solución.
Hemos informado a las filiales del motivo por el que esto ocurre, tranquilizándoles de que ya está identificado, que nos sigan informando cada vez que ocurre para que Binpar pueda valorar si es algo que se soluciona sin realizar ninguna acción o si es necesario reiniciar el sistema. 
De cara al cliente responderemos:
Estamos estudiando cómo mejorar y que mientras tanto les pedimos que pasados unos minutos vuelvan a intentarlo. Y que cuando les ocurra avisen a la filial para que nos lo puedan comunicar y Vosotros toméis nota de lo ocurrido.

**Comment by CristianBinpar** [comment]
Cierro este issue, que se reabrirá con casos puntuales que nos notificarán en el 24x7, como comentamos.
