### ISSUE TITLE
1032016 16-09-26 Universidad Tecnológica de Pereira

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#4]
Institución: Universidad Tecnológica de Pereira
http://gestor.medicapanamericana.com/tables/institution.aspx?id=398&setOppenerVal=398
Descripción: Desde esta institución nos solicitan acceso por IP para Eureka. Por una lado Ipv4 lo he metido en DRM sin problemas, pero también solicitan IPv6 2801:0:4c0::/48, ¿esto lo puedo meter en el DRM tal cual? No he querido hacer la prueba sin consultaros por si provocamos algún error. Por favor, confirmadnos si se puede hacer o de qué forma tendría que hacerlo.
[1032016 16-09-26 Universidad Tecnológica de Pereira.xlsx](https://github.com/BinPar/eBooks/files/500144/1032016.16-09-26.Universidad.Tecnologica.de.Pereira.xlsx)

**Comment by CristianBinpar** [comment]
http://ipv6.ztsoftware.net/ipv4-to-ipv6/
