### ISSUE TITLE
1282016 Gerencia Hospitalaria 

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#40]
El título: http://www.medicapanamericana.com/Libros/Libro/5702/eBook-Gerencia-Hospitalaria.html?TipoContenido=Electr%C3%B3nicos&buscador=Gerencia%20h Gerencia Hospitalaria ha sido solicitado por una institución en Colombia. Sin embargo no aparece en el DRM para activarlo.
He preguntado a Verónica y esto es lo que me ha contestado: 
_Está a la venta web pero no en nuestra filial y supongo que Eureka! y DRM estén asociados a los movimientos que se hagan en las fichas de los eBooks desde España asociados a nuestra filial.
He preguntado y estamos esperando a que llegue la obra en papel a nuestro país para realizar el lanzamiento del libro en las dos versiones (es una obra de Colombia). Entiendo, pues, que hasta que no lo pongamos a la venta aquí, no saldrá enlazado (la pista la da el problema de la fecha, que venía con la fecha asociada nuestra filial).
La puesta en venta está prevista para finales de este mes.

Casi estoy convencida de que es por eso… pero si quieres asegurar cómo va el sistema preguntando a Binpar, pues supongo que no estaría mal

Qué podemos hacer para activarlo a Colombia antes de que se publique en España?
La institución que lo ha solicitado es: http://gestor.medicapanamericana.com/tables/institution.aspx?id=398
Gracias

**Comment by CristianBinpar** [comment]
@ajarillo 

Es un tema recurrente, ya hemos comentado en otras ocasiones los campos necesarios en información de filial para que aparezca en Eureka. No es necesario que esté a la venta para que cumpla esas condiciones.

Igualmente, ya está publicado en la filial España.
