### ISSUE TITLE
1302016 9788498355345 Enfermedad de Alzheimer y otras Demencias - Error tipografía

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#43]
Título 9788498355345 Enfermedad de Alzheimer y otras Demencias nos reportan un error en la tipografía; en la parte II y en el inciso A vienen mezcladas mayúsculas con minúsculas del libro (imagino que tiene que ver con la incrustación de fuentes, revisé y al parecer el problema se presenta en el índice y en las letras I de los autores y de los títulos de los temas a lo largo de la obra).
![1](https://cloud.githubusercontent.com/assets/22492646/19641571/935220f0-99e1-11e6-8c39-42ea77624311.jpg)
![3](https://cloud.githubusercontent.com/assets/22492646/19641576/980838d2-99e1-11e6-8593-b22a9ac57988.jpg)
![2](https://cloud.githubusercontent.com/assets/22492646/19641577/98220fa0-99e1-11e6-9873-1a79c530a3f5.jpg)

**Comment by ajarillo** [comment]
Esta mañana hemos pedido confirmación a México para que vea si ya le aparece bien.

**Comment by ajarillo** [comment]
Buen día, te comento que ya se ha corregido el problema, sin embargo, me llama la atención que con un Zoom de 170 se siguen viendo las letras “i” como mayúsculas, pero ajustándolo a 160 se ven como minúsculas, mira:

Zoom 170
 
![170](https://cloud.githubusercontent.com/assets/22492646/19775976/a77c704c-9c72-11e6-9485-32dc5020a866.png)


Zoom 160
 
![160](https://cloud.githubusercontent.com/assets/22492646/19775980/acb68b56-9c72-11e6-8496-5debc5c61b5e.png)


Quedo al pendiente de tus comentarios.

**Comment by AguedaBinpar** [comment]
@ajarillo mañana miro bien lo del último correo enviado relacionado con el zoom

**Comment by AguedaBinpar** [comment]
@ajarillo Alicia, las capturas son de méxico, o son tuyas replicando el problema? 

No se replica en mi máquina... yo borré cache durante las correcciones, si son tuyas, puedes mirarlo ahora a ver?

**Comment by ajarillo** [comment]
Hola,
es de México. Yo he probado con GChrome y Firefox y no puedo reproducirlo.
Aviso a México para que borre caché y vuelva a probar. También preguntaré versión de navegador.

**Comment by AguedaBinpar** [comment]
perfecto, esperamos a ver que nos dicen

**Comment by AguedaBinpar** [comment]
Alicia

noticias de mexico en cuanto al trema del "zoom"?

**Comment by ajarillo** [comment]
Aún nada, se lo recuerdo.
