### ISSUE TITLE
1312016 Competencias en las Practicas Clinicas en Ciencias de la Salud. Mat compl no se ve en Edge

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#44]
Martiañez. Competencias-en-las-Practicas-Clinicas-en-Ciencias-de-la-Salud. Material complementario no se ve en Edge. http://www.medicapanamericana.com/materialesComplementarios/Martiañez/visor.aspx

La captura podéis encontrarla aquí: https://drive.google.com/file/d/0B-MQEOwVhqd0Rlp5VmlUcW5yNXM/view?usp=sharing

**Comment by CristianBinpar** [comment]
@ajarillo 

se la paso a José, y que entre por web si nos lo aprueba.

Hay que hacer una adaptación de estilos en los materiales orientada a Edge.
