### ISSUE TITLE
1322016 Duda en materiales complementarios

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#45]
Necesito habilitar estos materiales complementarios y no los encuentro en el gestor. Puedes darme alguna pista sobre cómo buscarlos?
-   http://www.medicapanamericana.com/Libros/Libro/4630/eBook-Atencion-Integral-de-la-Infertilidad.html?TipoContenido=&buscador=atencion integral de la infer
- Y de estos hay varios electrónicos y no sé cuál incluir: https://www.medicapanamericana.com/materialesComplementarios/Campbell-10/Campbell.aspx

**Comment by CristianBinpar** [comment]
@ajarillo 

debes buscarlo desde la obra en cuestión:
http://gestor.medicapanamericana.com/tables/work.aspx?id=4630

El material es:
http://gestor.medicapanamericana.com/tables/complementaryMat.aspx?id=586

**Comment by CristianBinpar** [comment]
Depende, si es el completo parece que es el siguiente:
Campbell / Walsh. Urología [EBO:45876]
