### ISSUE TITLE
1332016 Borrar ebooks en colección 

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#46]
No puedo borrar ebooks en Colección dentro del DRM. Esto es lo que me sale: 
![screencapture-gestor-medicapanamericana-tables-collectionsebook-aspx-1477427496621](https://cloud.githubusercontent.com/assets/22492646/19759609/2986ce2e-9c2e-11e6-8921-c238a15452d6.png)
Antes tenía permisos no sé que puede haber pasado.

**Comment by drnachio** [comment]
Habría que reindexar la tabla

**Comment by ajarillo** [comment]
Ok, gracias cuando lo tengáis avisadme por favor.

**Comment by CristianBinpar** [comment]
Se está realizando, confirmamos en breves

**Comment by CristianBinpar** [comment]
Listo Ali,
revisa a ver si ya se puede

**Comment by ajarillo** [comment]
Acabo de probar con otro navegador, por si acaso y nada: 
![image](https://cloud.githubusercontent.com/assets/22492646/19765412/8b4e3894-9c48-11e6-8c8e-045e20608b5b.png)

**Comment by drnachio** [comment]
La tabla a reindexar es ebookCollections no @CristianBinpar ?

**Comment by CristianBinpar** [comment]
Reindexada también la tabla ebookCollections, a ver ahora...

**Comment by ajarillo** [comment]
Lo siento sigo igual, he probado en GChrome en incógnito: 
![image](https://cloud.githubusercontent.com/assets/22492646/19775264/2e2f4c20-9c70-11e6-87e5-580cf0a106e8.png)

**Comment by CristianBinpar** [comment]
@ajarillo me puede pasar la url de la colección y el eBook a borrar?

Gracias.

**Comment by ajarillo** [comment]
Hola Cristian,
eliminé la colección completa y la rehice pues Elena Feduchi necesitaba el acceso a Universidad Francisco de Vitoria ayer a las 15h.
Te valdría cualquiera, pues no podía borrar ningún ebook dentro de una colección. Acabo de realizar una prueba desde: http://gestor.medicapanamericana.com/tables/collection.aspx?id=787 y http://gestor.medicapanamericana.com/tables/collection.aspx?id=890 y puedo eliminar títulos.
Cierro incidencia.
Gracias

**Comment by CristianBinpar** [comment]
Perfecto
