### ISSUE TITLE
1352016 Incluir en un solo archivo metadatos de suscripción Universidad Andrés Bello

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#49]
Necesitamos generar un solo archivo MARC con todos los registros. Podéis descargar un ejemplo de registro marc que les ha enviado otro proveedor a ver si podemos hacerlo igual (**cambiar la extensión a .mrk, es que si no, no podía subirlo**).
Los metadatos que hay que incluir son los de los siguientes títulos: 
http://gestor.medicapanamericana.com/tables/collection.aspx?id=878
![image](https://cloud.githubusercontent.com/assets/22492646/19963805/644cab7e-a1be-11e6-8f5c-1ef6be436f41.png)

**Comment by CristianBinpar** [comment]
@ajarillo 

sería nuevo desarrollo, ¿Eureka v2.2?

por cierto, ¿dónde está el archivo?

**Comment by ajarillo** [comment]
No, es algo puntual para una institución que nos lo ha solicitado, como lo que hicimos hace poco para México.
Adjunto archivo.
[Access medicina actualizado a agosto 2016.mrk.docx](https://github.com/BinPar/eBooks/files/568815/Access.medicina.actualizado.a.agosto.2016.mrk.docx)

**Comment by CristianBinpar** [comment]
Perfecto,

replicamos el procedimiento de la última ocasión.

Si se vuelve a solicitar no sería mala idea incluirlo como funcionalidad.

**Comment by AguedaBinpar** [comment]
Alicia, me pasas el excell desde el que has hecho la imagen de nuestro listado?

Gracias

**Comment by AguedaBinpar** [comment]
Alicia,

esta incluido este ebook

9789500604680 Histología y Embriología del ser humano. Bases celulares y moleculares. 4ª Edicion
Eynard 

En la actualidad esta la 5ª edicion a la venta en la web

Es correcta la edción en la colleción?

**Comment by ajarillo** [comment]
Hola Águeda, gracias por informarnos.
Por favor, incluye los dos. 
Gracias
Alicia





 De:   A.Gamez <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Mention <mention@noreply.github.com> 
 Enviado:   03/11/2016 16:15 
 Asunto:   Re: [BinPar/eBooks] 1352016 Incluir en un solo archivo metadatos de suscripción Universidad Andrés Bello (#49) 


Alicia, 
esta incluido este ebook 
9789500604680 Histología y Embriología del ser humano. Bases celulares y moleculares. 4ª Edicion
 Eynard  
En la actualidad esta la 5ª edicion a la venta en la web 
Es correcta la edción en la colleción? 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by AguedaBinpar** [comment]
Ok, incluyo ambos

gracias

**Comment by AguedaBinpar** [comment]
Alicia,

te voy a mandar por email normal un rar con el archivo de todas las obras juntas en xml, marc (marc21) mrk y mark8 (UTF-8) por si acaso

que por aqui no me deja aduntarlo
