### ISSUE TITLE
1042016 16-09-27 Reporte Universidad Latinoamericana

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#5]
Institución: Universidad Latinoamericana
http://gestor.medicapanamericana.com/tables/institution.aspx?id=2
No aparecen algunos de los títulos contratados dentro de Eureka, Hemos revisado el DRM y no vemos nada que nos llame la atención.
- Cuidados paliativos. No aparece en Eureka a pesar de estar incluido en las licencias activas 825 y 824 del DRM.
- 9789500604635 CECCOTTI:Diag. Clinica Estomatologica-e. También activado en DRM y no se visualiza en el Eureka de esta institución. No aparece en Eureka a pesar de estar incluido en las licencias activas 825 y 824 del DRM.
Navegador y dispositivo utilizados: PC. Google Chrome
[1042016 16-09-27 Reporte Universidad Latinoamericana.xlsx](https://github.com/BinPar/eBooks/files/500155/1042016.16-09-27.Reporte.Universidad.Latinoamericana.xlsx)

**Comment by CristianBinpar** [comment]
Manuel, Alicia,

hemos detectado uno de los problemas recurrentes en las incidencias. Estamos en el caso de los ebooks que no aparecen en Eureka y si están contratados.

Ahora mismo en Eureka las instituciones entran como Filial España, estos ebooks no tienen fecha de publicación en España. Para que apareciera el ebook se tendría que añadir una fecha de publicación para su obra en España.

![unnamed](https://cloud.githubusercontent.com/assets/17255550/19185153/add1dfec-8c80-11e6-9437-89fd9fe33fe9.png)

Así se solucionaría el problema de la ULA entre otras instituciones.

Un saludo

**Comment by ajarillo** [comment]
Hola, esto cómo lo incluimos?
Gracias
 
De: CristianBinpar [mailto:notifications@github.com] 
Enviado el: viernes, 7 de octubre de 2016 11:25
Para: BinPar/eBooks <ebooks@noreply.github.com>
CC: ajarillo <ajarillo@medicapanamericana.es>; Author <author@noreply.github.com>
Asunto: Re: [BinPar/eBooks] 1042016 16-09-27 Reporte Universidad Latinoamericana (#5)
 
Manuel, Alicia,
hemos detectado uno de los problemas recurrentes en las incidencias. Estamos en el caso de los ebooks que no aparecen en Eureka y si están contratados.
Ahora mismo en Eureka las instituciones entran como Filial España, estos ebooks no tienen fecha de publicación en España. Para que apareciera el ebook se tendría que añadir una fecha de publicación para su obra en España.
Así se solucionaría el problema de la ULA entre otras instituciones.
Un saludo
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by ajarillo** [comment]
No tengo permisos creo para acceder a esta pantalla. Qué fecha debo poner en estos títulos?
Hay forma de saber en cuáles ocurre esto? o debo ir uno por uno? Afecta esto a algo de JGalán en la web?
Gracias

**Comment by CristianBinpar** [comment]
Podéis solicitarlo a José Galán / Vero para los casos de eBooks que no aparezcan en Eureka.

Con que cambien ese campo es suficiente.

**Comment by CristianBinpar** [comment]
En esta ocasión, hemos avisado a Vero para que actualice estos 2.

**Comment by ajarillo** [comment]
Acabo de hablar con Vero y comprobar que estos dos títulos están en Eureka.
México ya ha sido informado y he enviado screenshot con la prueba.
Gracias
