### ISSUE TITLE
1362016 UAM Xochimilco

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#51]
México nos reporta una incidencia sobre Eureka y el visor. Hay una universidad:
http://gestor.medicapanamericana.com/tables/institution.aspx?id=401
Que tiene dos problemas:
- El logo no se visualiza correctamente porque no tenemos unas indicaciones que dar al cliente para que nos envíe su logo y el que nos mandan se ve muy mal. Qué medidas les podemos dar para que pueda mejorarse la visualización del logo?
- Eureka y el visor funcionan correcto, pero al estar durante unos instantes, lleva al usuario sin que este haga nada a la página de bibliotecas de la web.
Tenéis toda la información sobre las pruebas que ha hecho Silvia en los archivos adjuntos.
Entiendo que esto es S1 ya que la biblioteca no puede tener acceso a Eureka nada más que por unos segundos.
[16-11-14 Reporte UAM Campus Xochimilco Actualización.xlsx](https://github.com/BinPar/eBooks/files/591453/16-11-14.Reporte.UAM.Campus.Xochimilco.Actualizacion.xlsx)
[16-11-14 UAM Campus Xochimilco Actualización.docx](https://github.com/BinPar/eBooks/files/591454/16-11-14.UAM.Campus.Xochimilco.Actualizacion.docx)

**Comment by FaustoBinpar** [comment]
1. El logo de esta Universidad tiene mucho ancho y poca altura (tendría que ser una imagen cuadrada), estos son ejemplos de logos para su correcta visualización:
http://gestor.medicapanamericana.com/tables/institution.aspx?id=1
http://gestor.medicapanamericana.com/tables/institution.aspx?id=2
http://gestor.medicapanamericana.com/tables/institution.aspx?id=244 

2. He revisado los logs y no veo errores, he accedido por ip y no tengo ningun error. Al ser un acceso por url referida no puedo replicar el error de la Universidad, necesitaría unas credenciales y el portal para poder acceder de este modo

**Comment by ajarillo** [comment]
Gracias Fausto, le he pedido más información a Silvia.
Un saludo,
Alicia
 
De: FaustoBinpar [mailto:notifications@github.com] 
Enviado el: miércoles, 23 de noviembre de 2016 13:08
Para: BinPar/eBooks <ebooks@noreply.github.com>
CC: ajarillo <ajarillo@medicapanamericana.es>; Author <author@noreply.github.com>
Asunto: Re: [BinPar/eBooks] 1362016 UAM Xochimilco (#51)
 
1.      El logo de esta Universidad tiene mucho ancho y poca altura (tendría que ser una imagen cuadrada), estos son ejemplos de logos para su correcta visualización:
http://gestor.medicapanamericana.com/tables/institution.aspx?id=1
http://gestor.medicapanamericana.com/tables/institution.aspx?id=2
http://gestor.medicapanamericana.com/tables/institution.aspx?id=244
2.      He revisado los logs y no veo errores, he accedido por ip y no tengo ningun error. Al ser un acceso por url referida no puedo replicar el error de la Universidad, necesitaría unas credenciales y el portal para poder acceder de este modo
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by ajarillo** [comment]
Hola Fausto,
No me había dado cuenta de que en el documento que te adjunté a la hora de dar de alta la incidencia ya estaban las credenciales. Por favor, revisa toda la documentación adjunta en cada incidencia.

Me contesta:
_Sobre las credenciales para acceder, te comento que en el segundo reporte que envié estaban incluidas en el campo que agregué al Excel “Detalles de Acceso a la plataforma de la institución”, de cualquier forma las indico nuevamente a continuación.
 
http://biblioteca.xoc.uam.mx/login.html?destino=panamericana
Matrícula o Número económico= 35587
NIP= 3055
 
También te comento que hace un momento realicé un nuevo intento tanto en Google Chrome como en Internet Explorer y la incidencia persiste; después de unos breves instantes de haber accedido a Eureka me envía a la página de Panamericana._

Gracias

**Comment by miguelBinpar** [comment]
Efectivamente, así es.

Credenciales:
http://biblioteca.xoc.uam.mx/login.html?destino=panamericana
Matrícula o Número económico: 35587
NIP: 3055

**Comment by FaustoBinpar** [comment]
Alicia he visto el fallo y la solución
El portal de la Universidad tiene un protocolo http **(http**://biblioteca.xoc.uam.mx/login.html?destino=panamericana) y hace una llamada a Eureka con protocolo https (**https**://www.medicapanamericana.com/digital/ebooks/buscador)

La llamada deberia se http (**http**://www.medicapanamericana.com/digital/ebooks/buscador)

Con este cambio por parte de ellos se solucionara el problema

**Comment by ajarillo** [comment]
Gracias Fausto
