### ISSUE TITLE
1372016 Vista de títulos no suscritos

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#52]
La Universidad Pompeu Fabra: http://gestor.medicapanamericana.com/tables/institution.aspx?id=345
![imagen1](https://cloud.githubusercontent.com/assets/22492646/20299961/424be428-ab1d-11e6-8411-db84d14ad493.png)
Estamos a punto de cerrar una oferta con ellos y les aparecen más títulos de los que deberían. Los tuvieron en su momento, pero decidieron quitar unos pocos y quedarse sólo con 5. Estamos a punto de cerrar una oferta con ellos y el que no solucionemos esto hasta el miércoles nos puede suponer que crean que no damos un servicio rápido de atención de incidencias.
Eliminé todas las licencias que tenían y lo hice todo de nuevo, para ver si así se solucionaba, pero no es así. De hecho he realizado la prueba desde mi casa, adjunto pantallazo IP 79.145.162.239 y sigo viendo más títulos de los que deberían ver.
Quedamos a la espera de solución. Podría ser antes del miércoles? He llamado a Cristian pero está reunido.

**Comment by ajarillo** [comment]
Hola Cristian.
Según hablamos la semana pasada, esta incidencia estaría resuelta para mañana tras la vuelta de Fausto.
La biblioteca nos lo acaba de preguntar. Por favor, confírmame que esto sigue en la cola para realizarlo mañana.
Gracias

**Comment by CristianBinpar** [comment]
Así es

**Comment by ajarillo** [comment]
Gracias J
 
De: CristianBinpar [mailto:notifications@github.com] 
Enviado el: miércoles, 23 de noviembre de 2016 12:50
Para: BinPar/eBooks <ebooks@noreply.github.com>
CC: ajarillo <ajarillo@medicapanamericana.es>; Author <author@noreply.github.com>
Asunto: Re: [BinPar/eBooks] 1372016 Vista de títulos no suscritos (#52)
 
Así es
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by FaustoBinpar** [comment]
Solucionado,
He refrescado las licencias y listo
http://www.medicapanamericana.com/drm/data/reloadlicenses...

**Comment by ajarillo** [comment]
Hola Fausto,
el actualizar las licencias lo realicé varias veces a lo largo de estos días y seguía viendose los títulos no suscritos.
Lo actualizaba en la URL: http://www.medicapanamericana.com/drm/data/reloadlicenses/?psw=alicia es correcta, verdad?
Voy a confirmarlo con el cliente,
Gracias
Alicia
