### ISSUE TITLE
1382016 Universidad Católica de Manizales no aparece en URL Estadísticas

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#53]
La Universidad Católica de Manizales http://gestor.medicapanamericana.com/tables/institution.aspx?id=384 no aparece en la URL: http://www.medicapanamericana.com/drm/Home/Counter necesitamos que aparezca.
Gracias

**Comment by ajarillo** [comment]
Esta tampoco está: Universidad Católica de Pereira: http://gestor.medicapanamericana.com/tables/institution.aspx?id=383

**Comment by ajarillo** [comment]
Ni esta: http://gestor.medicapanamericana.com/tables/institution.aspx?id=386
Todas tienen en común que son de Colombia.

**Comment by ajarillo** [comment]
Han tenido que renovar el periodo de demo porque no pueden acceder a las estadísticas de lo que se ha usado nuestros compañeros de la filial.

**Comment by CristianBinpar** [comment]
Vamos a planificar esta tarea para el próximo lunes.

**Comment by CristianBinpar** [comment]
@ajarillo estas instituciones no aparecen en la lista hasta que se produce algún acceso, es automático y no hay ningún tipo de restricción por filial, por ejemplo.

2 de las 3 instituciones ya aparecen desde hace algunos días, y para la otra (id=383) aún no se han recogido estadísticas.

**Comment by CristianBinpar** [comment]
En cuanto haya estadísticas aparecerá en el listado
