### ISSUE TITLE
1392016 Integración metadatos con OCLC

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#54]
Necesitamos presupuesto para cumplir los requisitos que nos solicitan en el documento adjunto. Es el mismo caso que tenemos pendiente con otro distribuidor EBSCO incluido en GitHub con anterioridad. Pero este nos resulta aún más urgente porque está pendiente de aprobación un presupuesto de 40.000 €.

Por favor, contestadnos lo antes posible. Para que Alfonso nos de el ok.
[OCLC_WorldCat_knowledge_base_data_format_v7(1)(4).pdf](https://github.com/BinPar/eBooks/files/599801/OCLC_WorldCat_knowledge_base_data_format_v7.1.4.pdf)

Gracias

**Comment by CristianBinpar** [comment]
Presupuesto enviado vía email.
