### ISSUE TITLE
Intregrar Eureka en otras plataformas - Info para Pfizer

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#56]
Hola, nos confirmasteis que esto es posible, pero para llamar al laboratorio Pfizer que estaba interesado pero desechó la oferta por no poder realizar esta integración. 

Nos interesaría retomar el contacto con él, pero necesitamos más detalles para "cautivarle".
Gracias

**Comment by CristianBinpar** [comment]
@ajarillo en la última reunión mensual que tuvimos con Manuel, le expliqué como funcionaría esta integración.

Lo podemos revisar en la reunión que tengamos a principios de enero y enseñaros algún ejemplo.
