### ISSUE TITLE
Estadísticas Eureka

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#57]
Para la consulta de las estadísticas en Eureka, para las instituciones, ya creasteis un botón para cambiar de año. Ese botón aparecerá ya directamente en enero por defecto con el año 2017?

Para información interna utilizamos la URL que nos proporcionasteis: http://www.medicapanamericana.com/drm/Home/Counter pero esto no tiene opción para ver las de 2017 sin perder las de 2016. necesitaríamos acceso a los dos años.

**Comment by CristianBinpar** [comment]
@ajarillo para información interna puedes cambiar el parámetro en la URL, te funcionará sin problemas desde el día 1 de 2017.
EJ: http://www.medicapanamericana.com/drm/Home/CounterStats/256**?Year=2017**

**Comment by CristianBinpar** [comment]
Actualizado el año 2017 como opción en el desplegable.
