### ISSUE TITLE
Activar DTM para Universidad de Zaragoza

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#58]
Institución: http://gestor.medicapanamericana.com/tables/institution.aspx?id=285
IP: 155.210.0.0-155.210.255.255
Fecha caducidad: 31/12/2017

**Comment by miguelBinpar** [comment]
Buenos días,

Me pongo con esto. Sólo recordaros que el funcionamiento es independiente del DRM, por lo que si queréis tener la licencia en el gestor, podéis hacerlo a mano (no tiene ningún efecto real en el acceso).

Os aviso cuando esté.

**Comment by ajarillo** [comment]
Gracias. Así lo haré.
 
 
 
De: Miguel Rodríguez Rosales [mailto:notifications@github.com] 
Enviado el: martes, 22 de noviembre de 2016 13:34
Para: BinPar/eBooks <ebooks@noreply.github.com>
CC: ajarillo <ajarillo@medicapanamericana.es>; Author <author@noreply.github.com>
Asunto: Re: [BinPar/eBooks] Activar DTM para Universidad de Zaragoza (#58)
 
Buenos días,
Me pongo con esto. Sólo recordaros que el funcionamiento es independiente del DRM, por lo que si queréis tener la licencia en el gestor, podéis hacerlo a mano (no tiene ningún efecto real en el acceso).
Os aviso cuando esté.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Listo y en principio funcionando.
