### ISSUE TITLE
1052016 16-09-27 Reporte Universidad Valle de México

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#6]
Institución: Universidad del Valle de México
http://gestor.medicapanamericana.com/tables/license.aspx?id=884
descripción: Con ayuda del documento adjunto podéis realizar un entrada al sistema de la Universidad del Valle de México y ver desde donde nos solicitan acceso. Según Fausto la URL es http://sfxna11.hosted.exlibrisgroup.com/52UVM, es la misma URL parcial que metió Silvia en el gestor DRM. Aún así la biblioteca sigue sin poder tener acceso a los títulos de esta forma.
La URL parcial es una de las mejoras que incluimos junto a Eureka 2.1, pero no la hemos podido probar, porque para esta universidad, que es para la que se solicitó este desarrollo, aún se puede entrar por esta vía.
Navegador y dispositivo utilizados: PC. Google Chrome
[1052016 16-09-27 Documentación para prueba Universidad Valle de México.xlsx.docx](https://github.com/BinPar/eBooks/files/500173/1052016.16-09-27.Documentacion.para.prueba.Universidad.Valle.de.Mexico.xlsx.docx)
[1052016 16-09-27 Reporte Universidad Valle de México.xlsx](https://github.com/BinPar/eBooks/files/500174/1052016.16-09-27.Reporte.Universidad.Valle.de.Mexico.xlsx)

**Comment by CristianBinpar** [comment]
Como os comentamos hace alguna semanas la URL desde la que acceden no es esa

**Comment by ajarillo** [comment]
Si, esto ya lo sabemos. Pero en vez de darnos la URL desde la que deberían acceder para que la incluyamos en el DRM nos piden que identifiquemos nosotros la URL desde la que nos hacen la petición.
Les he solicitado que hagan la prueba y que nos digan la IP desde la que acceden en la prueba y que junto a la hora de acceso, podríamos identificar la URL pero se niegan a darnos esa información y por eso quieren la TLF del día 17 de octubre.
la información que les he solicitado es correcta para ver desde que URL nos hacen la petición de acceso? O pensáis que es mejor continuar con la TLC?
Gracias

**Comment by CristianBinpar** [comment]
Está perfectamente solicitado.
Esperamos que nos lo pasen para detectar la URL.

Si hay que hacer una TLC reabrimos el issue.

**Comment by ajarillo** [comment]
Disuclpa que abra esta incidencia de nuevo.
Aquí hay dos puntos a tener en cuenta.
- por una parte la URL http://sfxna11.hosted.exlibrisgroup.com/52UVM desde la que nos están pidiendo acceso y que nosotros ya hemos detectado (Fausto lo confirmó hace días) es una URL referida parcial, deberían de acceder a Eureka pero no lo hacen, esto hasta donde sabemos en un fallo nuestro que hay que revisar. este punto está pendiente desde la TLC de Nacho de este verano con ellos, donde les dijo que la URL referida parcial estaría disponible en agosto, con la subida de la nueva versión. Ellos parece que están haciendo todo bien, hasta que demostremos lo contrario. Sin embargo nosotros la petición de esa URl referida parcial que está incluida en el DRM y desde la que nos hacen la petición no les damos acceso. Este punto es el que hay que revisar para cerrar la incidencia.
- por otra parte está el acceso proxy que nos llega a través de una IP diferente a la que nos dicen, pero desde donde hacen la prueba no quieren decirnos la IP. Eso es lo que les he solicitado. Para este punto abriré una nueva incidencia en el momento en que me faciliten la IP.
Gracias

**Comment by ajarillo** [comment]
He vuelto a hacer una prueba con esta universidad, a ver si de esta forma podemos acelerar el proceso de resolución de la incidencia. Aquí teneís la URL de la ventana emergente desde la cual voy a hacer la petición de acceso a nuestros ebooks:
![image](https://cloud.githubusercontent.com/assets/22492646/19384903/3d2dee34-920c-11e6-8650-c4adca0b3c62.png)
Y esta es la siguiente página que nos aparece después de hacer la petición. La URL desde la que la realizamos es la que está en DRM: 
![image](https://cloud.githubusercontent.com/assets/22492646/19384930/6b570660-920c-11e6-9675-0bd257aed4b7.png)
Vuestro turno.
Gracias

**Comment by CristianBinpar** [comment]
Solucionado.

**Comment by ajarillo** [comment]
Genial!! Es súper buena noticia. Acabo de probar y de avisar a México.
