### ISSUE TITLE
Activar DTM Universidad Pompeu Fabra

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#60]
Hola, 

Necesitamos activar el DTM para la IP 84.89.128.0-84.89.159.255,193.145.32.0-193.145.63.255
Institución: http://gestor.medicapanamericana.com/tables/institution.aspx?id=345
Caducidad: 31/12/2017

Gracias

**Comment by miguelBinpar** [comment]
Acceso creado. Debería estar funcionando ya.

**Comment by ajarillo** [comment]
Gracias



 De:   Miguel Rodríguez Rosales <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   24/11/2016 11:14 
 Asunto:   Re: [BinPar/eBooks] Activar DTM Universidad Pompeu Fabra (#60) 


Acceso creado. Debería estar funcionando ya. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.
