### ISSUE TITLE
BUCLE (venta cerrada recientemente) necesita un solo archivo .mrc

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#64]
BUCLE, que ha suscrito recientemente todo el catálogo nos solicita un archivo .mrc de los que suele crear Águeda con todos los materiales incluidos en su colección en DRM: http://gestor.medicapanamericana.com/tables/collection.aspx?id=896

Lo necesitaríamos para el día 9 como muy tarde, puede ser?
antes en la web teníamos un acceso directo en el que se descargaban todos los títulos (ellos han contratado todo el catálogo) e igual puede valer pero no sé en qué formato de archivo estaba.
Gracias

**Comment by CristianBinpar** [comment]
@ajarillo vamos a pasar el de la bibliografía completa.

Sino habría que hacer un desarrollo específico para que se adapte a cada institución.

Hoy lo tenéis.

**Comment by ajarillo** [comment]
Hola,


el de la bibliografía completa incluye ediciones antiguas junto a las nuevas? Por ejemplo las dos ediciones del Feduchi que hay en ebook?


Gracias
Alicia



 De:   CristianBinpar <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Mention <mention@noreply.github.com> 
 Enviado:   07/12/2016 12:42 
 Asunto:   Re: [BinPar/eBooks] BUCLE (venta cerrada recientemente) necesita un solo archivo .mrc (#64) 


@ajarillo vamos a pasar el de la bibliografía completa. 
Sino habría que hacer un desarrollo específico para que se adapte a cada institución. 
Hoy lo tenéis. 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by CristianBinpar** [comment]
Casi seguro que sí.

**Comment by ajarillo** [comment]
Entonces no es lo que nos han pedido.
Por favor, podría valorar el realizar un desarrollo para que nos genere a petición un archivo de metadatos con los títulos contratados por una institución?
Son los que han realizado un contrato a 2 años por 40.000 € cada año.
Gracias
Alicia



 De:   CristianBinpar <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Mention <mention@noreply.github.com> 
 Enviado:   07/12/2016 15:28 
 Asunto:   Re: [BinPar/eBooks] BUCLE (venta cerrada recientemente) necesita un solo archivo .mrc (#64) 


Casi seguro que sí. 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by CristianBinpar** [comment]
ok, presupuestamos entonces

**Comment by ajarillo** [comment]
Hola, 
Por favor, cuando podáis pasarnos las instrucciones para poder descargar el archivo que necesita la biblioteca.
Gracias

**Comment by CristianBinpar** [comment]
Buenos días @ajarillo ,

la url a emplear sería la siguiente:

http://www.medicapanamericana.com/marc21.aspx?**BIBLIOGRAPHY**=XML&**INS_ID**=1

en el parámetro BIBLIOGRAPHY puedes indicar la versión del marc21 que quieres, es decir:

- XML

- DAT

y en el parámetro INS_ID le indicas el ID de la institución. Si tienes dudas puedes entrar en la ficha de la institución en el gestor y sería el id que aparece al final de la URL: http://gestor.medicapanamericana.com/tables/institution.aspx?id=1

**Comment by ajarillo** [comment]
Hola, al descargar el archivo de la URL: http://www.medicapanamericana.com/marc21.aspx?BIBLIOGRAPHY=XML&INS_ID=250 descargo el archivo y está vacío, pues al abrirlo con el bloc de notas no hay nada escrito.
De hecho estoy intentando adjuntarlo y el GitHub me dice que pruebe con otro archivo porque ese está vacío. Vosotros lo habéis probado en producción. Por favor, ya limaremos esta función más adelante, pero de verdad que para esta universidad en concreto necesitamos el archivo con mucha urgencia. Podríais enviarme el archivo?
Gracias

**Comment by CristianBinpar** [comment]
Ya funciona correctamente en producción.

Además, hemos enviado el archivo vía email
