### ISSUE TITLE
Exlibris

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#65]
Hola Cristian,
Por fin Exlibris ha dado señales de vida. Te copio más abajo el email donde nos solicitan algunas cosas, por favor, revísadlo y presupuestadlo en cuanto podáis. El acceso para la IP que nos solicitan ya se lo he activado.
Gracias

_Hello Manuel,
 
As you may know, Ex Libris is now a ProQuest company. 
As such, we index content for inclusion in both the Summon and Primo discovery services.
We have recently launched a new, shared ingestion process for Summon and Primo content that is increasing the velocity of new content added to our Primo Central Index.
We have completed analysis of the Editorial Medica Panamericana data for ingestion in our Primo Central Index (and there is a chance that you also need to communicate with our Summon colleagues to verify they have the most up-to-date metadata feed).
Meanwhile, we also need to re-instate an IP authorization (our address is 212.179.71.70) for accessing records on your native site – to be sure that the links displaying in each of your records resolve as expected – for us and for the mutual customers.
 
We would also need to obtain an up-to-date version of the title list that was supplied to us on your FTP facility:
Host: 80.28.219.213
User: ExLibris
Pass: ExLibrisB1nP4R
Path: /WebPanamericana/MARC21
 
What is the expected frequency of updates for this list?
To automate maintenance of this list in our knowledgebase, we need the title list file to be always placed at the same location under the same name. Older versions can be kept aside with a timestamp added.
 
Thank you in advance,
Olga Edelman_

**Comment by CristianBinpar** [comment]
@ajarillo presupuesto enviado.

**Comment by ajarillo** [comment]
Hola Cristian,
Lo último que tengo de este tema es lo siguiente. Como ya ha pasado el día 1, voy a preguntarles si nos pueden confirmar que la carga se realizara correctamente.
Gracias
_De: Cristian Alvarez <cristian@binpar.com> 
Para: Manuel Júlbez Campos <mjulbez@medicapanamericana.es> 
CC: Alicia Jarillo <ajarillo@medicapanamericana.es>, Rosa Martínez <rosa.martinez@medicapanamericana.es> 
Enviado: 19/12/2016 13:51 
Asunto: Re: EBSCO Rellenar formulario 
Buenas Manuel,
 
aprovecho para comentaros que la primera de las tareas ya está realizada:
 
•       Integración de los contenidos de Editorial Médica Panamericana con ExLibris de forma automática y periodicidad mensual
 
Se ejecutará el día uno de cada mes a las 06 de la mañana.
 
abz_
