### ISSUE TITLE
Univ Zaragoza ve título no suscrito

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#67]
Nos ha ocurrido de nuevo, que la institución: http://gestor.medicapanamericana.com/tables/institution.aspx?id=285 con licencia: http://gestor.medicapanamericana.com/tables/license.aspx?id=905 ve el título: Anatomía Humana: Manual de prácticas basadas en el razonamiento clínico, de Guzmán López

Hace poco nos pasó con la Univ Pompeu Fabra y Fausto me dijo que lo único que había hecho era actualizar los accesos. La URL que yo tengo para hacerlo es: http://www.medicapanamericana.com/drm/data/reloadlicenses/?psw=alicia
Ejecutando esta URL siguen viendo el título, la URL ha cambiado??
Gracias

**Comment by FaustoBinpar** [comment]
Buenos días Alicia,

La url no ha cambiado 

He vuelto a ejecutar la url 

Podrías decirme si el error persiste? 

Un saludo

**Comment by ajarillo** [comment]
Hola Fausto, ya está solucionado.
No entiendo porqué cuando yo lo actualizo no funciona.
Un saludo,
Alicia
