### ISSUE TITLE
1072006 Mis ebooks en la web con Safari

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#7]
Tenemos a los usuarios: 
María Isabel  García Bernal: ibernal@us.es
Federico Portillo Pacheco federico.portillo@uca.es
Utilizan Safari, tienen activados tanto en el gestor como en PRM una serie de ebooks, sin embargo cuando van a Mis ebooks en la web no los visualizan.
Los usuarios también han probado a acceder desde la web estando registrados, buscando el libro en el buscador y tampoco tienen acceso.
En el caso del Silverthorn lo tienen activado y si lo ven, pero el Cano de la Cuerda y el Mezquita no.
Tenemos la duda de si esta incidencia hay que incluirla en este gestor o no. Pero José Galán me dice que Ana le comentó que esto igual pasaba porque Fausto tocó algo. En las etiquetas no tenemos la de la web, porque eso yo no os lo reporto, el contacto es Jose G, ya me contaréis.

**Comment by miguelBinpar** [comment]
Hola Alicia,

Estoy revisando este tema y no veo que coincida la información del gestor con lo que veo. Es decir, María Isabel tiene 3 ebooks, pero dos caducados, por lo tanto sólo debería ver uno y así es como lo veo yo si accedo con su usuario (en Safari). Por su parte, Federico tiene dos ebooks (uno de ellos duplicado), pero todos caducados, por lo tanto no debería ver ninguno.

Este tema sigue vigente? Ha cambiado algo?

Un saludo,

**Comment by ajarillo** [comment]
Hola Miguel, he hablado con los implicados en EMP y de momento no sigue vigente.
Cierro, y si fuera necesario volvería a abrir.
Gracias
