### ISSUE TITLE
Error visualización 9788498359640 Endocrinología

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#71]
Usuario: glopezosteo@gmail.com 
Título: http://www.medicapanamericana.com/VisorEbookV2/Ebook/9788498359640
Dispositivo: tablet BQ Aquaris M10 FHD. 
Descripción: Las columnas de texto se superponen. Las imágenes las ve bien. Adjunto imagen,
![2016_12_29_15 53 05](https://cloud.githubusercontent.com/assets/22492646/21762552/933716f2-d659-11e6-8199-d42db831c3c1.png)

He probado en tlf  Samsung S7 - navegador Chrome ocurre lo mismo, por ejemplo en la página 19.
Ya le pedimos al usuario que probara con Chrome y le ocurre lo mismo.

**Comment by AguedaBinpar** [comment]
Hicimos pruebas en iOS y Android, sin poder reproducir el error, usando Safari, explorador nativo de Android, además de chrome en ambos dispositivos.

Tampoco se reproduce en web (comprobado en chrome, explorer y firefox)

Por la captura, es un problema relacionado con las tipografías, no esta cargando las que debería (el texto principal es una tipografía con serifas no de palo) en esta obra.

Debería verse así:
![image](https://cloud.githubusercontent.com/assets/22906572/21800361/972223be-d71d-11e6-951e-f32e39abfccb.png)

**Comment by ajarillo** [comment]
Hola Águeda, qué podemos hacer?
En el S7 Samsung también sucede lo mismo.
El cliente nos dice que así no puede leer el libro.


Gracias
Alicia



 De:   A.Gamez <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   10/01/2017 10:15 
 Asunto:   Re: [BinPar/eBooks] Error visualización 9788498359640 Endocrinología (#71) 


Hicimos pruebas en iOS y Android, sin poder reproducir el error, usando Safari, explorador nativo de Android, además de chrome en ambos dispositivos. 
Tampoco se reproduce en web (comprobado en chrome, explorer y firefox) 
Por la captura, es un problema relacionado con las tipografías, no esta cargando las que debería (el texto principal es una tipografía con serifas no de palo) en esta obra. 
Debería verse así:
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Hola Alicia,

Más allá del Samsung 7, sabemos en qué navegador? O sucede en todos los navegadores con el Samsung 7?

El tema es que @AguedaBinpar ha detectado perfectamente el error: la fuente no se está cargando y es lo que descuadra todo. Me llamaba la atención que el resto de fuentes sí estaban siendo cargadas. He echado un vistazo y la fuente que genera el problema es "Times New Roman". Esta fuente, al igual que "Arial" y no sé si "Fontana" (ya me queda muy lejos) son especiales para el conversor, puesto que no las extrae como hace con el resto. Esto es así porque supuestamente son fuentes genéricas que vienen incluidas en cualquier sistema operativo, de ahí que no sea necesario cargarlas como hacemos con las demás. Por eso mismo es realmente extraño el problema, con la complicación añadida de que no tenemos -que yo sepa- ninguno de los dos dispositivos para hacer pruebas.

Voy a intentar investigar y decirte algo más, mientras tanto nos vendría bien saber con qué navegador se ve mal con el Samsung 7.

Un saludo

**Comment by miguelBinpar** [comment]
Tras varias pruebas no hemos conseguido ningún resultado.
Me temo que por alguna razón, los sistemas que experimentan el problema no tienen la fuente "Times New Roman", aunque me extraña mucho.

La única solución que se me ocurre sería reconvertir con la opción para que no optimice fuentes y de esta manera, extraiga también las fuentes que no se extraen (Times, Arial, Verdana), aunque entiendo que el ebook ya estará publicado y demás. Lo perfecto habría sido detectar este error antes de publicarlo.

**Comment by ajarillo** [comment]
Hola Miguel,


Gracias por tu respuesta. Lo he probado con el navegador que viene por defecto en el tlf Android S7.
Cuando podías nos contáis que podríamos hacer.
Mil gracias




 De:   Miguel Rodríguez Rosales <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   12/01/2017 10:12 
 Asunto:   Re: [BinPar/eBooks] Error visualización 9788498359640 Endocrinología (#71) 


Hola Alicia, 
Más allá del Samsung 7, sabemos en qué navegador? O sucede en todos los navegadores con el Samsung 7? 
El tema es que @AguedaBinpar ha detectado perfectamente el error: la fuente no se está cargando y es lo que descuadra todo. Me llamaba la atención que el resto de fuentes sí estaban siendo cargadas. He echado un vistazo y la fuente que genera el problema es "Times New Roman". Esta fuente, al igual que "Arial" y no sé si "Fontana" (ya me queda muy lejos) son especiales para el conversor, puesto que no las extrae como hace con el resto. Esto es así porque supuestamente son fuentes genéricas que vienen incluidas en cualquier sistema operativo, de ahí que no sea necesario cargarlas como hacemos con las demás. Por eso mismo es realmente extraño el problema, con la complicación añadida de que no tenemos -que yo sepa- ninguno de los dos dispositivos para hacer pruebas. 
Voy a intentar investigar y decirte algo más, mientras tanto nos vendría bien saber con qué navegador se ve mal con el Samsung 7. 
Un saludo 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Hola Alicia,

En el último mensaje del issue ya os doy la única solución posible. No veo manera de arreglarlo sin tener que convertir de nuevo, así que debéis evaluar si merece la pena reconvertir (yo desconozco si el ebook se publicó hace mucho, si ya se ha vendido, etc).

Un saludo

**Comment by ajarillo** [comment]
Gracias Miguel, no saben aún si reconvertirlo o no.
Si te parece bien cierro la incidencia y en caso de convertirlo de nuevo la abriría de nuevo.

Un saludo
