### ISSUE TITLE
Integración con Summon

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#72]
Hola,
Nos dicen desde SUmmon (es también de Proquest, como Exlibris) que necesita que subamos a este otro ftp lo mismo que hemos subido con la tarea #65. Y que les confirmemos lo que nos preguntan.

Please can you confirm whether it is a full xml file ?   If so; this can be uploaded to the “full folder” within the ftp.

ftp.summon.serialssolutions.com

UID: medicapanamericana-primary

PW: Y3ma7sM6Jw

Gracias

**Comment by CristianBinpar** [comment]
Perfecto,

indico la ruta local donde lo guardamos para proceder a la subida:

/WebPanamericana/MARC21/InformesExLibris

**Comment by CristianBinpar** [comment]
Ya está subida la información a su FTP.

Recordar que no tenemos un archivo (XML) sino que se optó por un XLS.
