### ISSUE TITLE
Activar DTM para Real Academia Española

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#73]
Ahora mismo están sin acceso.
Licencia: http://gestor.medicapanamericana.com/tables/license.aspx?id=770
Activar hasta 15/01/2018

Gracias

**Comment by miguelBinpar** [comment]
Hola Alicia,
Podrías pedirles que prueben y me confirmas si ya pueden entrar?

Un saludo!

**Comment by ajarillo** [comment]
Gracias Miguel, acabo de escribir al cliente, en cuanto me confirmen, te digo.
Un saludo
Alicia



 De:   Miguel Rodríguez Rosales <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   10/01/2017 11:26 
 Asunto:   Re: [BinPar/eBooks] Activar DTM para Real Academia Española (#73) 


Hola Alicia,
 Podrías pedirles que prueben y me confirmas si ya pueden entrar? 
Un saludo! 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by ajarillo** [comment]
Hola Miguel,
me dice que les sigue pidiendo correo electrónico y contraseña.
Normalmente hasta que nos subís versión de la web no se hace efectivo, no?
Gracias



 De:   Miguel Rodríguez Rosales <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   10/01/2017 11:26 
 Asunto:   Re: [BinPar/eBooks] Activar DTM para Real Academia Española (#73) 


Hola Alicia,
 Podrías pedirles que prueben y me confirmas si ya pueden entrar? 
Un saludo! 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Ahora lo comprobaré, pero este caso es distinto. Lo que precisa subir versión es la creación de un nuevo acceso. En este caso, el acceso existe. De hecho había dos accesos, uno hasta enero de 2016 y otro hasta febrero de 2017. He borrado el primero y he extendido el segundo (hasta la fecha que comentabas). Dado que todavía estaban dentro de las fechas habilitadas (deberían haber tenido acceso hasta febrero), pensé que el problema se debía a los warnings, que he bajado a -500 como hemos hecho ya algunas veces.

Si tras todo esto me dices que siguen sin poder entrar, voy a necesitar que les pidas que comprueben la IP desde la que están accediendo y que te pasen la hora exacta de los intentos que realicen.

Cuando me pases la info comprobamos los logs y te comento.

**Comment by ajarillo** [comment]
Hola Miguel ya funciona.
Debe ser que no se le actualizaron los cambios inmediatamente.
Gracias por tu ayuda.
