### ISSUE TITLE
Actualización de Metadatos en Xercode

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#74]
Hola,
Hicimos una carga de metadatos en CSV para este distribuidor, pero ya se ha quedado desactualizada.
Necesitaría poder obtener estos datos de nuevo.
Se me ocurre que como BUCLE, los que nos han pedido el marc con el catálogo completo a lo mejor podría servir también a Xercode, qué opináis?
Además nos solicitan las imágenes de las portadas cuyo título nombre de archivo sea el EAN.

La Universidad de Santiago no podrá ver algunos de los títulos que han contratado sin que les enviemos estos metadatos actualizados  a Xercode.

**Comment by ajarillo** [comment]
Los títulos que necesitamos que vea Santiago serían:
SUSCRIPCIÓN
Biología Celular y Molecular

Biología Molecular del Gen

DSM-5. Manual Diagnóstico y Estadístico de los Trastornos Mentales

Fundamentos de Bioquímica

Introducción a la Biología Celular
TEST
DSM-5. Casos clínicos

Psicología del lenguaje

**Comment by ajarillo** [comment]
Hola Miguel,
Nos reclaman esto de nuevo. Esta biblioteca ya pagó estos títulos en suscripción par todo el añoy si no les damos acceso, el año que viene no renovarán. Sólo pueden acceder desde la plataforma de Xercode, por lo que necesitamos que los metadatos estén en Xercode.
Me podrías dar fecha?

**Comment by CristianBinpar** [comment]
Hola @ajarillo ,

entendimos por tu mensaje anterior que haríamos una integración a través de formato marc21, y con la nueva funcionalidad ya puedes exportar la información de cualquier entidad.

Dime si necesitáis algo más.

**Comment by CristianBinpar** [comment]
Os pasa Águeda en breves las portadas en un zip.

**Comment by AguedaBinpar** [comment]
Alicia te las paso por un correo, que no consigo adjuntar el archivo por aqui

**Comment by ajarillo** [comment]
He enviado los metadatos a Xercode y de momento parece que está todo correcto. Cierro incidencia.
Gracias
