### ISSUE TITLE
1082016 Sin acceso a algunos ebooks a través de IP desde Eureka

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#8]
Hora 17:36 IP 95.127.90.226
Podemos entrar en Eureka, nos reconoce la IP y podemos realizar búsquedas y previsualizar dentro del buscador.
Si queremos acceder a algunos títulos mediante el botón de Abrir contenido nos lleva a Preguntas frecuentes. Por ejemplo cualquiera de los 2 títulos: Neuropsicología de la Adicción y Intoxicaciones Agudas por Drogas de Abuso.
El Feduchi si lo vemos.
Sin embargo si accedemos a Eureka desde nuestro usuario de EMP (no por IP) sí podemos acceder al visor desde el botón de Abrir contenido.
La duda que nos entra es si este problema lo están teniendo todos nuestros usuarios que se conectan por IP e incluso si los que están a través de URL referida o token también pueden verse afectados.
Hoy y mañana estamos en un congreso y no podremos mostrar el botón Mi colección por no utilizar el acceso por IP.

**Comment by CristianBinpar** [comment]
Debería estar solucionado.

**Comment by ajarillo** [comment]
No hemos podido reproducirlo de nuevo, con lo que ciertamente entendemos que está solucionado. Gracias
