### ISSUE TITLE
UPO Sevilla, tiene problemas para acceder al DTM.

### ISSUE THREAD

**Issue by Julbesito** [BinPar/eBooks#82]
Hola Acabamnos de recibir un mail de la UPO en Sevilla donde nos reflejan que no se puede acceder al DTM.
Por favor Miguel, podríais mirar dónde está el error?
![20170123 upo dtm](https://cloud.githubusercontent.com/assets/22503990/22204214/fe0c8922-e170-11e6-9f12-e665d5403d25.png)
Te indicamos estos otros datos de IP y hora.

Hora de acceso: 13:13
IP: 193.147.185.18

Esta licencia está para un Master en concreto de traduccion en UPO, podríamos ver una resolucion cercana en el tiempo?

Saludos y Graciassss

**Comment by miguelBinpar** [comment]
Hola Manuel,

Tema solucionado. Habían llegado al número máximo de 'warnings'. He vuelto a resetearlos.
Relativo a este tema, recuerdo que la idea era que cuando esto pasara le llegara un correo a @ajarillo avisando. Esto se llegó a hacer? Llegó a funcionar? Por tenerlo en cuenta y/o revisarlo.

Por cierto, si puedes recuerda asignarme la tarea por defecto a mí. En principio me enteraré igual, pero así nos aseguramos del todo.

Cierro tarea (y la paso a 'DONE').

Saludos

**Comment by Julbesito** [comment]
Okis miguel.
 
Mil gracias.
 
Creo que no habíamos hecho nada referente al tema de Alicia.
Hicimos algo con la UNAV pero no sé como al final se definió el tema.
 
Gracias de nuevo
 
 
Manuel
De: Miguel Rodríguez Rosales [mailto:notifications@github.com] 
Enviado el: lunes, 23 de enero de 2017 18:21
Para: BinPar/eBooks <ebooks@noreply.github.com>
CC: Manuel <mjulbez@medicapanamericana.es>; Assign <assign@noreply.github.com>
Asunto: Re: [BinPar/eBooks] UPO Sevilla, tiene problemas para acceder al DTM. (#82)
 
Hola Manuel,
Tema solucionado. Habían llegado al número máximo de 'warnings'. He vuelto a resetearlos.
Relativo a este tema, recuerdo que la idea era que cuando esto pasara le llegara un correo a @ajarillo avisando. Esto se llegó a hacer? Llegó a funcionar? Por tenerlo en cuenta y/o revisarlo.
Por cierto, si puedes recuerda asignarme la tarea por defecto a mí. En principio me enteraré igual, pero así nos aseguramos del todo.
Cierro tarea (y la paso a 'DONE').
Saludos
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Intentaré revisarlo pero me suena que algo había hecho (por Carlos). Otra cosa es que no acabara de quedar listo o que directamente no funcionara.

A ver si consigo sacar un hueco para esto, entiendo que sería muy positivo que se notifique a Alicia automáticamente de estos casos y que ella se anticipe al reporte de la incidencia solucionando la papeleta en el gestor (le explicaría a Alicia cómo hacerlo).
