### ISSUE TITLE
Información sobre estadísticas visible en Google

### ISSUE THREAD

**Issue by ajarillo** [BinPar/eBooks#88]
Hola,

Acabo de buscar un EAN de un título de EMP en Google y aparece como resultado en las primeras posiciones las estadísticas de varias universidades de forma abierta.
Esto es muy urgente que desaparezca, es información que estamos dando a la competencia y es confidencial de unas universidades a otras.

Gracias

**Comment by ajarillo** [comment]
![captura de pantalla 2017-02-09 a las 9 55 22](https://cloud.githubusercontent.com/assets/22492646/22777834/d5f168e4-eeb4-11e6-9225-02f40e250d5b.png)

**Comment by miguelBinpar** [comment]
Hola Alicia,

Acabo de modificar el fichero robots.txt de la web para que los buscadores no indexen las rutas que comienzan con "/drm/Home/CounterStats/". Tardará un tiempo en tener el efecto deseado, es decir, estas páginas tardarán en desaparecer de los resultados de los buscadores.

**Comment by ajarillo** [comment]
Gracias Miguel, si te parece bien, lo incluyo en la carpeta in progress hasta que nos aseguremos que está eliminado, te parece?
Es para que no se nos olvide comprobarlo dentro de un tiempo.









 De:   Miguel Rodríguez Rosales <notifications@github.com> 
 Para:   BinPar/eBooks <eBooks@noreply.github.com> 
 CC:   ajarillo <ajarillo@medicapanamericana.es>, Author <author@noreply.github.com> 
 Enviado:   15/02/2017 19:27 
 Asunto:   Re: [BinPar/eBooks] Información sobre estadísticas visible en Google (#88) 


Hola Alicia, 
Acabo de modificar el fichero robots.txt de la web para que los buscadores no indexen las rutas que comienzan con "/drm/Home/CounterStats/". Tardará un tiempo en tener el efecto deseado, es decir, estas páginas tardarán en desaparecer de los resultados de los buscadores. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by miguelBinpar** [comment]
Me parece perfecto
